In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split


In [3]:
df=pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
# X = df.drop('Species', axis=1) # X is the independent variables in our dataset
# y = df['Species'] # y is the dependent variable in our dataset
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)



In [5]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB().fit(X_train, y_train)
model

GaussianNB()

In [6]:
y_pred= model.predict(X_test) #now predicting our model to our test dataset
print(y_pred)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica']


In [7]:
# from sklearn.metrics import confusion_matrix,accuracy_score

accuracy_score = accuracy_score(y_test, y_pred)
print (accuracy_score)


1.0


In [12]:
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix: ')
print(cm)
# ac1 = accuracy_score(y_test, y_pred)*100
# print('Accuracy Score:')
# print(ac1)

Confusion Matrix: 
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]


In [16]:
# Extract values from the confusion matrix
tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else cm.ravel()[[3, 0, 1, 2]]




In [17]:
# Compute accuracy
accuracy = (tp + tn) / (tp + tn + fp + fn)
# Compute error rate
error_rate = (fp + fn) / (tp + tn + fp + fn)

# Compute precision
precision = tp / (tp + fp)

# Compute recall
recall = tp / (tp + fn)




C:\Users\ASUS\AppData\Local\Temp\ipykernel_20388\3176337064.py:10: RuntimeWarning: invalid value encountered in longlong_scalars
  recall = tp / (tp + fn)


In [18]:
# Print the performance metrics
print("True Positives:", tp)
print("False Positives:", fp)
print("True Negatives:", tn)
print("False Negatives:", fn)
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

True Positives: 0
False Positives: 19
True Negatives: 0
False Negatives: 0
Accuracy: 0.0
Error Rate: 1.0
Precision: 0.0
Recall: nan
